---
title: a recommended workflow
author: Tomoki Ishikawa
date: '2021-02-02'
slug: a-recommended-workflow
categories: []
tags: []
---

ウェブサイトを構築して展開するためには、多くの方法があります。

ウェブサイトの仕組みを完全に理解するためには、学ぶべき技術の数が非常に多いため、初心者の方には、この本の残りの部分を消化する必要がないように、1つのワークフローをお勧めしたいと思います。

これは間違いなく最適なワークフローではありませんが、最低限の技術的な詳細を知る必要があります。 

## 推奨ワークフロー
1. 新しいウェブサイトを始めるには  https:/themes.gohugo.io からテーマを選び、そのテーマの GitHubリポジトリへのリンクを見つけてください（https:/github.comuserrepo）。

2. RStudio で新しいプロジェクトを作成し、R コンソールで blogdown::new_site(theme = 'userrepo') というコードを入力します。 

3. 新しいサイトでしばらく遊んでみて、気に入らなければ上記の手順を繰り返し、そうでなければconfig.tomlのオプションを編集してください。
もし特定のオプションがわからない場合は、テーマのドキュメントを参照してください。すべてのオプションを変更する必要はありません。 ウェブサイトを編集するには  RStudio アドイン「Serve Site」をクリックして、RStudio Viewerでサイトをプレビューします。これは、RStudio プロジェクトを開くか Rセッションを再起動するたびに一度だけ行う必要があります。RStudio ツールバーの「ニット」ボタンはクリックしないでください。 

4. New Post" アドインを使用して新しい記事やページを作成し、コンテンツの書き込みを開始します。 必要に応じて「Update Metadata」アドインを使用してYAMLメタデータを修正します。 

5. GITやGitHubに慣れていない場合に、ウェブサイトを公開するにはRセッションを再起動し、blogdown::hugo_build()を実行します。
プロジェクトのルートディレクトリの下に公開ディレクトリを取得する必要があります。

6. https:/www.netlify.comにログインします（GitHubアカウントを持っている場合は、GitHubアカウントを使うことができます）。初めて公開する場合は新規サイトを作成し、そうでない場合は前回作成した既存のサイトを更新してください。公開したフォルダをファイルビューアからNetlifyのウェブページの "ここに静的サイトのあるフォルダをドラッグ＆ドロップしてください"と表示されている場所にドラッグ＆ドロップします。 ファイルを展開するNetlifyのための数秒を待ち、それはあなたにフォームrandom-word-1234567.netlify.comのランダムなサブドメインを割り当てます。それがまだ利用可能であれば、このランダムなサブドメインをより意味のあるものに変更することができます（そしてすべきです）。 

GITやGitHubに精通していれば、サイトを公開するのははるかに簡単になります。毎回手動で公開フォルダをアップロードするのではなく、継続的なデプロイのメリットを享受できるように、ウェブサイトのソースファイルを含むGitHubリポジトリからNetlify上に新しいサイトを作成することをお勧めします。このアプローチでは、ウェブサイトはHugo経由でNetlify上に構築できるので、ローカルでblogdown::hugo_build()を実行する必要はありません。